// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbmUKDr2d6DeElAGQifFnPKZPeRFeQBEI',
    appId: '1:102766618160:web:c4ac01f175e41c71baaff5',
    messagingSenderId: '102766618160',
    projectId: 'flutter-quiz-firebase',
    authDomain: 'flutter-quiz-firebase.firebaseapp.com',
    storageBucket: 'flutter-quiz-firebase.firebasestorage.app',
    measurementId: 'G-0FTSSFZSDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefjtDuUFHmHHHUWhBYLkG7lHkh-nAKQU',
    appId: '1:102766618160:android:d0736676e1ecb4ddbaaff5',
    messagingSenderId: '102766618160',
    projectId: 'flutter-quiz-firebase',
    storageBucket: 'flutter-quiz-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfwBs-MNpH0xL-3J6o7WuQFfGcxemQzGU',
    appId: '1:102766618160:ios:c413306803ad38b5baaff5',
    messagingSenderId: '102766618160',
    projectId: 'flutter-quiz-firebase',
    storageBucket: 'flutter-quiz-firebase.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfwBs-MNpH0xL-3J6o7WuQFfGcxemQzGU',
    appId: '1:102766618160:ios:c413306803ad38b5baaff5',
    messagingSenderId: '102766618160',
    projectId: 'flutter-quiz-firebase',
    storageBucket: 'flutter-quiz-firebase.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbmUKDr2d6DeElAGQifFnPKZPeRFeQBEI',
    appId: '1:102766618160:web:7196d0402f0d8b2abaaff5',
    messagingSenderId: '102766618160',
    projectId: 'flutter-quiz-firebase',
    authDomain: 'flutter-quiz-firebase.firebaseapp.com',
    storageBucket: 'flutter-quiz-firebase.firebasestorage.app',
    measurementId: 'G-VHDYEZLYVQ',
  );
}
